;;; startup-test.el --- Full configuration smoke tests -*- lexical-binding: t; -*-
;; Loaded by startup-check.sh after early-init, before init.el.
(require 'ert)

(defvar nd/startup-errors nil)
(defun nd/startup-record-warning (_type message &optional level &rest _)
  "Record errors caught by package setup instead of aborting init."
  (when (memq level '(:error :emergency)) (push message nd/startup-errors)))
(advice-add 'display-warning :before #'nd/startup-record-warning)

(ert-deftest nd/startup-loads-config-and-packages ()
  (should (>= emacs-major-version 31))
  (should-not init-file-had-error)
  (should-not nd/startup-errors)
  (should (file-equal-p user-init-file (expand-file-name "init.el" user-emacs-directory)))
  (should (file-in-directory-p user-emacs-directory (getenv "ARCMAC_STARTUP_ROOT")))
  (should (file-in-directory-p my/state-dir (getenv "ARCMAC_STARTUP_ROOT")))
  (should (equal user-full-name "Startup Test"))
  (dolist (feature '(evil evil-collection org org-ql undo-fu-session))
    (should (featurep feature)))
  (should evil-mode)
  (should (assoc "jm" org-capture-templates)))

(ert-deftest nd/startup-org-and-code-hooks-and-saving ()
  (let ((root (getenv "ARCMAC_STARTUP_ROOT")))
    (dolist (case `(("org/note.org" org-mode t)
                    ("other.org" org-mode nil)
                    ("org/code.el" emacs-lisp-mode nil)))
      (with-temp-buffer
        (setq buffer-file-name (expand-file-name (car case) root))
        (funcall (cadr case))
        (should (eq (not (null (funcall auto-save-visited-predicate))) (nth 2 case))))
      (should (default-value 'auto-save-visited-mode)))
    (with-temp-buffer
      (org-mode)
      (should org-modern-mode)
      (should (eq (lookup-key (evil-get-auxiliary-keymap org-mode-map 'normal)
                             (kbd "<leader>mE")) #'nd/org-meeting-details))
      (should (eq (lookup-key (evil-get-auxiliary-keymap org-mode-map 'normal)
                             (kbd "<leader>mw")) #'nd/org-waiting-for))
      (should (eq (lookup-key (evil-get-auxiliary-keymap org-mode-map 'normal)
                             (kbd "<leader>mU")) #'nd/org-project-update))
      (should (eq (key-binding (kbd "SPC n c e")) #'nd/contact-edit-details)))
    (dolist (binding '(("<leader>mw" . nd/org-waiting-for)
                       ("<leader>mU" . nd/org-project-update)))
      (should (eq (lookup-key (evil-get-auxiliary-keymap org-agenda-mode-map 'normal)
                             (kbd (car binding))) (cdr binding))))
    (should-not nd/startup-errors)))

(ert-deftest nd/startup-mail-sent-routing-treats-addresses-literally ()
  (require 'notmuch)
  (dolist (case '(("Alex <alex+work@example.org>" . "work/Sent +sent -inbox -unread")
                  ("alex+work@exampleXorg" . "primary/Sent +sent -inbox -unread")
                  ("Unknown <other@example.org>" . "primary/Sent +sent -inbox -unread")))
    (should (equal (cdr case)
                   (cdr (seq-find (lambda (rule) (string-match-p (car rule) (car case)))
                                  notmuch-fcc-dirs))))))

(ert-deftest nd/startup-mail-sync-uses-shared-command-and-queues-after-send ()
  (let (commands sentinel messages refreshed)
    (cl-letf (((symbol-function 'executable-find) (lambda (_) "/test/mail-sync"))
              ((symbol-function 'make-process)
               (lambda (&rest options)
                 (push (plist-get options :command) commands)
                 (setq sentinel (plist-get options :sentinel))))
              ((symbol-function 'message) (lambda (format &rest args)
                                            (push (apply #'format format args) messages)))
              ((symbol-function 'notmuch-refresh-all-buffers) (lambda () (setq refreshed t)))
              ((symbol-function 'process-status) (lambda (_) 'exit)))
      (nd/notmuch-sync)
      (should (equal '("/test/mail-sync") (car commands)))
      (nd/mail-push-sent)
      (should (equal '("/test/mail-sync" "--wait") (car commands)))
      (cl-letf (((symbol-function 'process-exit-status) (lambda (_) 75)))
        (funcall sentinel 'fake "done")
        (should-not refreshed)
        (should (equal "Mail sync already running" (car messages))))
      (cl-letf (((symbol-function 'process-exit-status) (lambda (_) 0)))
        (funcall sentinel 'fake "done")
        (should refreshed))
      (cl-letf (((symbol-function 'process-exit-status) (lambda (_) 1)))
        (funcall sentinel 'fake "done")
        (should (equal "Mail sync failed — see *notmuch-sync*" (car messages))))
      (cl-letf (((symbol-function 'executable-find) (lambda (_) nil)))
        (should-error (nd/notmuch-sync) :type 'user-error)
        (nd/mail-push-sent)
        (should (string-prefix-p "Mail sent; sync unavailable:" (car messages)))))))

(ert-deftest nd/startup-search-guidance-and-configured-org-directory ()
  (require 'consult-recoll)
  (let ((org-directory "/tmp/custom-notes/") searched)
    (cl-letf (((symbol-function 'executable-find) (lambda (_) nil)))
      (should-error (my/search-org) :type 'user-error)
      (should-error (nd/search-recoll) :type 'user-error))
    (cl-letf (((symbol-function 'executable-find) (lambda (_) "/test/program"))
              ((symbol-function 'consult-ripgrep) (lambda (directory) (setq searched directory)))
              ((symbol-function 'consult-recoll) (lambda () (interactive) (setq searched 'recoll)))
              ((symbol-function 'process-file) (lambda (&rest _) 1)))
      (my/search-org)
      (should (equal "/tmp/custom-notes/" searched))
      (should-error (nd/search-recoll) :type 'user-error)
      (let ((consult-recoll-search-flags '("-c" "/tmp/custom-recoll")))
        (cl-letf (((symbol-function 'process-file)
                   (lambda (&rest args)
                     (should (equal '("-c" "/tmp/custom-recoll" "-n" "1" "arcmac_index_probe")
                                    (nthcdr 4 args)))
                     0)))
          (nd/search-recoll)
          (should (eq 'recoll searched)))))))

(defun nd/prepare-startup-tests ()
  "Use temporary notes and dictionary before scratch/file mode hooks run."
  (let ((root (getenv "ARCMAC_STARTUP_ROOT")))
    (setq org-directory (expand-file-name "org/" root)
          nd/inbox-file (expand-file-name "inbox.org" org-directory)
          org-agenda-files nil
          org-journal-dir (expand-file-name "journal/" org-directory)
          ispell-personal-dictionary (expand-file-name "dictionary" root))
    (make-directory org-directory t)))

(defun nd/run-startup-tests ()
  "Check real initialization using only temporary notes and state."
  (condition-case error
      (let ((noninteractive t)) (ert-run-tests-batch-and-exit "^nd/startup-"))
    (error (princ (format "Startup test failure: %S\n" error)) (kill-emacs 1))))

(add-hook 'after-init-hook #'nd/prepare-startup-tests t)
(add-hook 'emacs-startup-hook #'nd/run-startup-tests t)
